import type { languages } from "monaco-editor";

export const zigMonarchLanguage = {
  keywords: [
    "addrspace",
    "align",
    "allowzero",
    "and",
    "anyframe",
    "anytype",
    "asm",
    "async",
    "await",
    "break",
    "callconv",
    "catch",
    "comptime",
    "const",
    "continue",
    "defer",
    "else",
    "enum",
    "errdefer",
    "error",
    "export",
    "extern",
    "fn",
    "for",
    "if",
    "inline",
    "linksection",
    "noalias",
    "noinline",
    "nosuspend",
    "opaque",
    "or",
    "orelse",
    "packed",
    "pub",
    "resume",
    "return",
    "struct",
    "suspend",
    "switch",
    "test",
    "threadlocal",
    "try",
    "union",
    "unreachable",
    "usingnamespace",
    "var",
    "volatile",
    "while",
  ],
  constants: ["true", "false", "null", "undefined"],
  types: [
    "u8",
    "u16",
    "u32",
    "u64",
    "u128",
    "usize",
    "i8",
    "i16",
    "i32",
    "i64",
    "i128",
    "isize",
    "f16",
    "f32",
    "f64",
    "f80",
    "f128",
    "bool",
    "void",
    "noreturn",
    "type",
    "anyerror",
    "comptime_int",
    "comptime_float",
  ],
  tokenizer: {
    root: [
      [/\/\/.*$/, "comment"],
      [/\/\*/, "comment", "@comment"],
      [/"([^"\\]|\\.)*$/, "string.invalid"],
      [/"/, "string", "@string"],
      [/'([^'\\]|\\.)*'/, "string"],
      [/@[A-Za-z_][\w]*/, "function.builtin"],
      [/\b0x[0-9a-fA-F_]+\b|\b\d[\d_]*(\.\d[\d_]*)?\b/, "number"],
      [/(\.)([A-Za-z_]\w*)(?=\s*\()/, ["delimiter", "function.method.call"]],
      [/(\.)([A-Z][A-Za-z0-9_]*)/, ["delimiter", "type.identifier"]],
      [/(\.)([A-Za-z_]\w*)/, ["delimiter", "property"]],
      [
        /\b[A-Za-z_]\w*(?=\s*\()/,
        { cases: { "@keywords": "keyword", "@default": "function.call" } },
      ],
      [
        /\b[A-Za-z_]\w*(?=\s*:)/,
        { cases: { "@keywords": "keyword", "@default": "variable.parameter" } },
      ],
      [/\b[A-Z][A-Za-z0-9_]*\b/, "type.identifier"],
      [
        /[A-Za-z_]\w*/,
        {
          cases: {
            "@keywords": "keyword",
            "@constants": "constant",
            "@types": "type",
            "@default": "identifier",
          },
        },
      ],
      [/==|!=|<=|>=|=>|<<|>>|\+%|-%|\*%|\+\||-\||\*\||\*\*|[-+*/%=&|^!<>?:~]+/, "operator"],
      [/[{}[\]();,.]/, "delimiter"],
    ],
    comment: [
      [/[^*/]+/, "comment"],
      [/\*\//, "comment", "@pop"],
      [/[*/]/, "comment"],
    ],
    string: [
      [/[^\\"]+/, "string"],
      [/\\./, "string.escape"],
      [/"/, "string", "@pop"],
    ],
  },
} satisfies languages.IMonarchLanguage;
